version: "3.5"

services:
  pingfederate:
    image: pingidentity/pingfederate:latest
    command: wait-for pingdirectory:389 -t 600 -- entrypoint.sh start-server
    env_file:
      - ./env-vars
    secrets:
      - devops-secret
    environment:
    - SERVER_PROFILE_URL=https://github.com/pingidentity/Customer360.git
    - SERVER_PROFILE_PATH=pingfederate
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999

  pingdirectory:
    image: pingidentity/pingdirectory:8.1.0.0-EA-edge
    env_file:
      - ./env-vars
    secrets:
      - devops-secret
    environment:
    - SERVER_PROFILE_URL=https://github.com/pingidentity/Customer360.git
    - SERVER_PROFILE_PATH=pingdirectory
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    ports:
      - 389:389
      - 1636:636
      - 1443:443
      - 2443:2443

  pingdatasync:
    image: pingidentity/pingdatasync:latest
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/Customer360.git
      - SERVER_PROFILE_PATH=pingdatasync
    env_file:
      - ./env-vars   
    secrets:
      - devops-secret
    #volumes:
    #   - ${HOME}/projects/devops/volumes/simple-sync.pingdatasync:/opt/out
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - 3636:636
      - 3443:443
  
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - 8080:8080
      - 8443:8443

  pingconfig:
    image: pricecs/pingconfigurator
    environment:
            # Collections: Solution - Customer360 --> Use Case: Consent Management - Config --> Use Case: PA as Proxy --> Use Case: PA with PF OIDC --> Use Case: Consent Enforcement
      - COLLECTIONS=https://www.getpostman.com/collections/344bbc13f4ccd4ebc5f5,https://www.getpostman.com/collections/eaa397bd3a35ef3095c1,https://www.getpostman.com/collections/4f27daff62383fd3f4ed,https://www.getpostman.com/collections/3db252f80d56599a5f46,https://www.getpostman.com/collections/a1378e567df17ff15f10
    volumes: 
      # An environment file should be injected into the image - this file should contain your specfic info and secrets
      - ./postman_vars.json:/usr/src/app/postman_vars.json  
    
  pingaccess:
    image: pingidentity/pingaccess:latest
    env_file:
     - ./env-vars
    secrets:
      - devops-secret
    ports:
     - 80:8080
     - 443:3000
     - 9000:9000

  pingconsent:
    image: pricecs/consentdashboard
    env_file:
      - ./env-vars
    ports:
      - 8088:80

  pingdatagov:
    image: pingidentity/pingdatagovernance:8.1.0.0-EA-edge
    environment:
     - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-Consent-Demo.git
     - SERVER_PROFILE_PATH=pingdatagovernance
    env_file:
     - ./env-vars
    secrets:
      - devops-secret
    ports:
     - 4443:443

  pingdatagov-pap:
    image: pingidentity/pingdatagovernancepap:8.1.0.0-EA-edge
    environment:
     - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-Consent-Demo.git
     - SERVER_PROFILE_PATH=pingdatagovernance-pap
    env_file:
     - ./env-vars
    secrets:
      - devops-secret
    ports:
     - 9443:9443

secrets:
  devops-secret:
    file: ${HOME}/.pingidentity/devops
